# 启动方法 VERSION=s1.0.6 (所需版本) BRANCH=test docker-compose up -d              down
# VERSION=s1.0.6 BRANCH=test ACTIVE=master docker-compose -f docker-compose_copy.yml down
version: '2'
services:
      #积分模块
  gruul-integral:
    image: 111.231.208.4:81/gruul/gruul-integral:$BRANCH-$VERSION
    restart: always
    container_name: gruul-integral-$VERSION
    ports:
      - "9700:9700"
    environment:
      - SERVER_PORT=9700
      - SPRING_PROFILES_ACTIVE=$ACTIVE
      - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
      #数据模块
  gruul-datasets:
     image: 111.231.208.4:81/gruul/gruul-datasets:$BRANCH-$VERSION
     restart: always
     container_name: gruul-datasets-$VERSION
     ports:
       - "9600:9600"
     environment:
       - SERVER_PORT=9600
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #用户模块
  gruul-account:
     image: 111.231.208.4:81/gruul/gruul-account:$BRANCH-$VERSION
     restart: always
     container_name: gruul-account-$VERSION
     ports:
        - "9450:9450"
     environment:
       - SERVER_PORT=9450
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #物流模块
  gruul-logistics:
     image: 111.231.208.4:81/gruul/gruul-logistics:$BRANCH-$VERSION
     restart: always
     container_name: gruul-logistics-$VERSION
     ports:
        - "9178:9178"
     environment:
       - SERVER_PORT=9178
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #团长模块
  gruul-assemble:
     image: 111.231.208.4:81/gruul/gruul-assemble:$BRANCH-$VERSION
     restart: always
     container_name: gruul-assemble-$VERSION
     ports:
        - "9210:9210"
     environment:
        - SERVER_PORT=9210
        - SPRING_PROFILES_ACTIVE=$ACTIVE
        - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #直播服务
  gruul-live:
     image: 111.231.208.4:81/gruul/gruul-live:$BRANCH-$VERSION
     restart: always
     container_name: gruul-live-$VERSION
     ports:
        - "9750:9750"
     environment:
         - SERVER_PORT=9750
         - SPRING_PROFILES_ACTIVE=$ACTIVE
         - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #商品服务
  gruul-goods:
     image: 111.231.208.4:81/gruul/gruul-goods:$BRANCH-$VERSION
     restart: always
     container_name: gruul-goods-$VERSION
     ports:
       - "9100:9100"
     environment:
       - SERVER_PORT=9100
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #短信服务
  gruul-sms:
     image: 111.231.208.4:81/gruul/gruul-sms:$BRANCH-$VERSION
     restart: always
     container_name: gruul-sms-$VERSION
     ports:
       - "9050:9050"
     environment:
       - SERVER_PORT=9050
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
         #社区配送
  gruul-shipping:
     image: 111.231.208.4:81/gruul/gruul-shipping:$BRANCH-$VERSION
     restart: always
     container_name: gruul-shipping-$VERSION
     ports:
       - "9177:9177"
     environment:
       - SERVER_PORT=9177
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
         #提货点
  gruul-point:
     image: 111.231.208.4:81/gruul/gruul-point:$BRANCH-$VERSION
     restart: always
     container_name: gruul-point-$VERSION
     ports:
       - "9179:9179"
     environment:
       - SERVER_PORT=9179
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #折扣服务
  gruul-discount:
     image: 111.231.208.4:81/gruul/gruul-discount:$BRANCH-$VERSION
     restart: always
     container_name: gruul-discount-$VERSION
     ports:
       - "9950:9950"
     environment:
       - SERVER_PORT=9950
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #商铺服务
  gruul-shops:
     image: 111.231.208.4:81/gruul/gruul-shops:$BRANCH-$VERSION
     restart: always
     container_name: gruul-shops-$VERSION
     ports:
       - "9210:9210"
     environment:
       - SERVER_PORT=9210
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #佣金服务
  gruul-finance:
     image: 111.231.208.4:81/gruul/gruul-finance:$BRANCH-$VERSION
     restart: always
     container_name: gruul-finance-$VERSION
     ports:
       - "9550:9550"
     environment:
       - SERVER_PORT=9550
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #订单服务
  gruul-order:
     image: 111.231.208.4:81/gruul/gruul-order:$BRANCH-$VERSION
     restart: always
     container_name: gruul-order-$VERSION
     ports:
       - "9150:9150"
     environment:
       - SERVER_PORT=9150
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #oss
  gruul-oss:
     image: 111.231.208.4:81/gruul/gruul-oss:$BRANCH-$VERSION
     restart: always
     container_name: gruul-oss-$VERSION
     ports:
       - "9300:9300"
     environment:
       - SERVER_PORT=9300
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #支付模块
  gruul-payment:
     image: 111.231.208.4:81/gruul/gruul-payment:$BRANCH-$VERSION
     restart: always
     container_name: gruul-payment-$VERSION
     ports:
       - "9350:9350"
     environment:
       - SERVER_PORT=9350
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
        #平台服务
  gruul-platform:
     image: 111.231.208.4:81/gruul/gruul-platform:$BRANCH-$VERSION
     restart: always
     container_name: gruul-platform-$VERSION
     ports:
       - "9200:9200"
     environment:
       - SERVER_PORT=9200
       - SPRING_PROFILES_ACTIVE=$ACTIVE
       - SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION=$VERSION
       #城市合伙人
  medusa-admin:
     image: 111.231.208.4:81/gruul/medusa-admin:$BRANCH-$VERSION
     restart: always
     container_name: medusa-admin-$VERSION
     ports:
       - "8001:80"
      #pc区域团长后台
  medusa-leader-admin:
     image: 111.231.208.4:81/gruul/medusa-leader-admin:$BRANCH-$VERSION
     restart: always
     container_name: medusa-leader-admin-$VERSION
     ports:
       - "8005:80"